
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  mac:
    macos:
      xcode: 11.7
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
workflows:
  build:
    jobs:
      
      - cypress/run:
          name: Mac test
          executor: mac , with-chrome
          browser: chrome
          record: true
