

version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:

macos:
    xcode: 10.1.0
win: circleci/windows@2.2.0
workflows:
  build:
    jobs:
      - cypress/run:
           name: Win test
          executor: win
      - cypress/run:
          name: Mac test
          executor: mac
      - cypress/run:
         record: true
