version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  aws-s3: circleci/aws-s3@3.0.0
workflows:
  build:
    jobs:
      - build     
jobs:
  build:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
        environment:
          ## this enables colors in the output
          CYPRESS_BASE_URL: https://nebula-qa2.fundthrough.com/signin
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run --record -b chrome
      - aws-s3/sync:
          from: ./cypress/reports/mochareports/report.html
          to: s3://ftautomation-artifacts-storage/$CIRCLE_BRANCH/$CIRCLE_SHA1/videos
      # - aws-s3/sync:
      #     from: ./cypress/screenshots
      #     to: s3://ftautomation-artifacts-storage/$CIRCLE_BRANCH/$CIRCLE_SHA1/screenshots
      # - aws-s3/sync:
      #     from: ./cypress/snapshots
      #     to: s3://ftautomation-artifacts-storage/$CIRCLE_BRANCH/$CIRCLE_SHA1/snapshots
    